<?php   
 echo '<left>';
 echo '<table border="1"  width="90%" bordercolor="#FFFFFF"  cellspacing="1" bordercolorlight="#FFFF44" bordercolordark="#44FFFF" cellpadding="2">';
 echo '<tr bgcolor="FFFF44">';
   echo '<td align=center>';
  echo '<a href="contact_results.php?quicksearch=staff"> Staff </a>';
  echo '</td>';
#  echo '<td align="right">Member:</td>';
    echo '<td align=center>';
  echo '<a href="contact_results.php?quicksearch=member&type=company">Member by Company </a>';
  echo '</td>';
      echo '<td align=center>';
  echo '<a href="contact_results.php?quicksearch=member&type=first">Member by First Name</a>';
  echo '</td>';
 echo '<td align=center>';
 echo '<a href="contact_results.php?quicksearch=A"> A </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=B"> B </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=C"> C </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=D"> D </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=E"> E </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=F"> F </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=G"> G </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=H"> H </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=I"> I </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=J"> J </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=K"> K </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=L"> L </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=M"> M </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=N"> N </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=O"> O </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=P"> P </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=Q"> Q </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=R"> R </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=S"> S </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=T"> T </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=U"> U </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=V"> V </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=W"> W </a></td>';  
  echo '<td align=center><a href="contact_results.php?quicksearch=X"> X </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=Y"> Y </a></td>';
  echo '<td align=center><a href="contact_results.php?quicksearch=Z"> Z </a></td>';
  echo '</tr>';
  echo '</table>';    
  echo '</left>';
 ?>